# -*- coding: utf-8 -*-
"""games.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iwqlv-5W_20iIiCEX2mBWPZa__A_Q3B0
"""

import numpy as np
import pandas as pd

data = pd.read_csv('all_games.csv')
data.head()

data.info

summary = data['summary']
summary
summaryIsolated = summary.str.lower().str.split()
summaryIsolated