# -*- coding: utf-8 -*-
"""gamesIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upAg50kEqT0cRck4P6kkkZIQWgaBuJZb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

df = pd.read_csv('/content/all_games.csv', encoding='utf-8')
df.head()

df.isnull().sum()

df.shape

df['summary'].fillna('Missing', inplace=True)

df.isnull().sum()

df.head()

df['platform'].value_counts()

"""## Data Cleaning"""

df[df['user_review']=='tbd']

df = df.drop(df[df['user_review'] == 'tbd'].index)

count_platform = df["platform"].value_counts().reset_index()
count_platform.columns = ["Platform", "Count"]
count_platform

"""## Count by platform"""

sns.catplot(x="Count", y="Platform", kind="bar", data=count_platform, height=6, aspect=3)
plt.title('Number of Games by Platform', fontsize=16)
plt.grid(True)

"""## Top 10 Games by User Review"""

import numpy as np

df['user_review'] = df['user_review'].astype(np.float)

top_user_score = df.sort_values(['user_review'], ascending=False)[:10]
top_user_score[['name', 'user_review']]

fig, ax = plt.subplots(figsize = (10, 5))
sns.barplot(x = top_user_score['user_review'], y = top_user_score['name'])
plt.xlim(9.3, 9.8)
plt.title('Top 10 Games by User Review ', fontsize = 16)
plt.xlabel('User Review Score', fontsize = 14)
plt.ylabel('Name', fontsize = 14)

"""## Top 10 Games by Meta Score"""

top_meta_score = df.sort_values(['meta_score'], ascending = False)[:10]
top_meta_score[['name', 'meta_score']]

fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(x=top_meta_score['meta_score'], y=top_meta_score['name'], 
            orient = 'h', 
            palette='flare')
plt.xlim(95, 100)
plt.title('Top 10 Games by Meta Score', fontsize=16)
plt.xlabel('Meta Score', fontsize=14)
plt.ylabel('Name', fontsize=14)

"""## Era that had the best video games"""

era = df
era['release_date'] = pd.to_datetime(era['release_date'])

era['year'] = df['release_date'].dt.year

era1 = era.groupby('year')

era2 = df.sort_values(['meta_score'], ascending = False)
era2[['year', 'meta_score']]

era2 = era.groupby('year')

era2.head()

era2['meta_score'].sum().sort_values(ascending = False).reset_index()

era3 = era2['meta_score'].sum().sort_values(ascending = False).reset_index()
era3.columns = ["year", "Total"]

sns.catplot(x="year", y="Total", kind="bar", data=era3, height=6, aspect=3)
plt.title("Year that had the best video games ( Popularity ) ")
plt.xlabel('Year')
plt.ylabel("Popularity of Video Games")
plt.grid(True)